site_name: CNIO Bioinformatics Unit documentation
site_url: https://cnio-bu.github.io
repo_url: https://github.com/cnio-bu/cnio-bu.github.io

theme:
  name: 'material'
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
extra_css:
  - css/main.css

nav:
  - Home: index.md
  - BU organisation:
    - Chat: org/chat.md
    - Calendar: org/calendar.md
  - Development:
    - 'Development guidelines': dev.md
  - HPC resources:
    - 'Usage': hpc/usage.md
    - 'Administration': hpc/admin.md
